### ISSUE TITLE
Magic Blue Version 10

### ISSUE THREAD

**Issue by RobertOnesim** [Betree/magicblue#14]
I have a bulb version 10 and I wasn't able to connect it ("Failed to connect to peripheral f8:1d:78:60:2a:5a, addr type: random"). I have found that addr_type should be public so I added the version 10 in the "if" statement.

![17580204_1514292525279968_1326844116_n](https://cloud.githubusercontent.com/assets/15925256/24450493/c6d7151c-1483-11e7-8eb8-4683e491a399.jpg)

**Comment by Betree** [comment]
Thanks for the report ! Did setting the address type to public fixed the problem ?
Have you tried running magicblueshell with just `-b 9` to set the bulb version to 9 and see if it was compatible ?

**Comment by Betree** [comment]
Oh I just saw your pull request, thank you for that :smiley:
