### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by StevenLooman** [Betree/magicblue#25]
Can you publish `magicblue` to pypi? This makes installation for https://github.com/xiaohuim/homeassistant-magicblue a bit easier. See [This tutorial](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi) for more instruction.

`homeassistant-magicblue` can then simply refer the egg by name (and version) and `home-assistant` does the rest.

**Comment by Betree** [comment]
Deployed on [Pypi](https://pypi.python.org/pypi/magicblue/0.4.2) (see commit f9a2bdf79746bc68493fb682477b21c3dc58e347)

**Comment by StevenLooman** [comment]
Thank you!
