### ISSUE TITLE
Multiple bulbs setup

### ISSUE THREAD

**Issue by Betree** [Betree/magicblue#27]
This question is often asked, how many bulbs can we handle at the same time ? There's no theoretical limit in this library, but maybe in `bluepy` ?

Any feedback on the subject would be welcome. I've personally ordered two more bulbs so I'll be able to check that in a few weeks.

**Comment by Betree** [comment]
@mouth4war This is really interesting. My setup is 2x`v10` (public address type) and 1x`v7` (random address type, same as your `v8`).

I've made some changes in [experiments/multi-bulbs](https://github.com/Betree/magicblue/tree/experiments/multi-bulbs) (commit 52fa1f093678bcc026ebac096ea857420b44c88d) to be able to use magicblueshell with multiple bulbs at the same time, which makes testing easier.

The two `v10` react pretty well, everything went fine. But when I try to use the `v7` at the same time as the two other, it randomly disconnects - maybe a conflict when using public and random at the same time.

**But regarding your problem**, my `v7` bulb mac address starts with `c7`, the two others with `f8`. Maybe some of you `v8` are using public and other random address type. If so, we should put this code @StevenLooman wrote before version checking :
```
# try using mac_address
if mac_address is not None:
    mac_address_num = int(mac_address.replace(':', ''), 16)
    if mac_address_num & 0xF00000000000 == 0xF00000000000:
        return btle.ADDR_TYPE_PUBLIC
```

The reason it works from magicblueshell but not HA must be that when calling `connect` from magicblueshell, it also scans the device address type and pass it to magicbluelib.

Can you try connecting to the bulb that have a MAC starting with `F` using public address type ?

**Comment by Betree** [comment]
For instance, the official android app also bugs when I try to use both types (v7/v10) at the same time.

**Comment by StevenLooman** [comment]
My mac address check is probably not complete or even invalid. The check I added worked for my bulbs (v10) and the one or articles about hacking the bulbs (can't remember which versions those were.) If you have/know something better...

Your best bet if so specify a version when connecting.

For the CLI: Please be aware that a new version of `bluepy` has been released. I noticed it can now take an entry from the scanner and automatically choose public/private.

**Comment by mouth4war** [comment]
I fixed the HA issue by copying the magicbluelib file to the deps folder (it maintains a local copy). So with RANDOM, I'm able to connect to all 5 bulbs with magicblueshell and HA both.

**Comment by mouth4war** [comment]
An update after observing the bulbs over a few days. They behave erratically in terms of maintaining a connection.  Different bulbs become unresponsive and cannot connect in magicblueshell at different times. Wait for a second or two and retry and viola, you're connected. Some "broken pipe" exceptions pop up from time to time.

I do remember similar behaviour in the android app. So maybe it's a v8 bulb thing.  How is the performance of the later bulbs for you guys? Are they consistent and responsive?

**Comment by Betree** [comment]
They do disconnect often, though v10 is more stable than v7 in my case.

However I found that using [@StevenLooman's fork](https://github.com/StevenLooman/homeassistant-magicblue) of the homeassistant component works really well as it now automatically reconnects and doesn't lock the all thing; from the user point of view it's transparent.

Another thing I noticed : the range for it to work properly is pretty short and very sensitive to obstacles.

**Comment by mouth4war** [comment]
Thanks for those tips! HA is not throwing up exceptions after switching to that fork. Bulbs seem more responsive, so far. 

I might just add 3 more of these to my room setup, despite white-only yeelights being around the same price. I prefer the aesthetics of this bulb more than the yeelight. I know I'll probably regret this!

**Comment by StevenLooman** [comment]
My v10s are also not 100% stable. Not from `home assistant` and not from the `magicblue` CLI or libs, although the CLI appears to be a bit more stable. All this is tried on a `Raspberry PI 3`.

Be sure to upgrade to the latest version of `bluepy`, that might further improve stability.

To be honest, if you want something (more) stable, you might want to choose another platform. I do have a (white-only) yeelight, but the light is very unnatural and unpleasant. I have no experience with the Philips HUE platform, or any of the compatible blubs.

**Comment by mouth4war** [comment]
I'm a lot happier with the performance with your fork, Steven. They are not 100% but almost 99% reliable now.  I ordered 3 more to complete my living room setup so I'll have 8 of these in my living room. 

I'm partial to ball/globe shaped bulbs so the yeelights and hues look unappealing to me. I can use them in lamps where the bulb isnt exposed, though.

OT: I also have 5 of [Philips/Xiaomi WW hubless step-less dimming globe-shaped bulbs (220v)](http://www.gearbest.com/smart-lighting/pp_644095.html) that work with the MiHome app and look great too. Wish these could be included in HA but it looks like they can't.

**Comment by StevenLooman** [comment]
Great! I'm curious to know how which versions you'll get and how they work.

For the Xiami bulbs, interesting. I have no experience with Xiaomi hardware, but am curious how these will work. I am guessing via bluetooth as well, but probably using another protocol.

There are some articles about the magicblue bulbs, on how to sniff the bluetooth traffic. Maybe you can do this and figure out any specifics from the used protocol.

**Comment by mouth4war** [comment]
So I got 3 v10 bulbs in the mail today. Plugged them in and tried magicblueshell and then adding to HASS.

They work fine!

HASS scenes take a while to set since the bulbs are sent commands one-by-one, so they respond one-by-one.

**Comment by StevenLooman** [comment]
The update should be happening in a separate thread and the `MainThread` should not get hung up on this. As soon as I have more time I'll look into this.

**Comment by Betree** [comment]
Closing this as [0.5 release](https://github.com/Betree/magicblue/releases/tag/0.5.0) allows for multiple bulbs usage in magicblueshell.

We probably have improvements and optimizations to do in the lib too but we'll open specific issues for them.
