### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by marksev1** [Betree/magicblue#3]
Betree, do these leds make a "mesh-network" so that they communicated peer-to-peer between the leds and then to the controller? Or do they all just simply connect to a controller? Do they have a separate bridge or no?

How much range do you get out of them?

**Comment by Betree** [comment]
Hello Mark, the LEDs communicate directly with a controller (the smartphone) via a Bluetooth LE connection. They do not have a separate bridge.

I haven't tested much the range but signal is still ok 10m cross the walls.

**Comment by marksev1** [comment]
Thanks for the answers!

**Comment by marksev1** [comment]
Just one more thing is it possible to change the color of multiple bulbs at the same time?

**Comment by Betree** [comment]
In theory, yes. See [this link about GATT](https://learn.adafruit.com/introduction-to-bluetooth-low-energy/gatt).

However I haven't tried it as I only posses one of these bulb.

**Comment by marksev1** [comment]
Thanks! On Adafruit I've also found this link: https://learn.adafruit.com/reverse-engineering-a-bluetooth-low-energy-light-bulb/explore-gatt
