### ISSUE TITLE
change magicblueshell.py to new bluepy lib

### ISSUE THREAD

**Issue by don41382** [Betree/magicblue#6]
Currently ```magicblueshell.py``` is still using the old library gattlib. This should be changed to the new bluepy library.

see http://ianharvey.github.io/bluepy-doc/ for details.

**Comment by Betree** [comment]
Done with commit [32aa1e777ef5cc929e2126636918e8957e9499c3](https://github.com/Betree/magicblue/commit/32aa1e777ef5cc929e2126636918e8957e9499c3) and available in [v0.2 release](https://github.com/Betree/magicblue/releases/tag/0.2).

Thanks for notifying this !
