### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jyshprd** [Betree/magicblue#9]
Hi there,

First of all thanks for all the hard work and I am sorry to come here to bother you with some probably very basic questions! I want to have my Raspberry control my Magic Blue bulbs (with a vocal assistant) and so far I have only managed to control the bulbs manually with Gatttool. I am not really experienced to say the least but you got to start somewhere I guess.

During the installation I am facing the following error message:

`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Dp955h-build/`

I have looked the error up and tried pretty much everything mentioned on StackOverflow.

EDIT: Managed to install, I was missing BluePy... BUT now I have another issue

> ubuntu@ubuntu:~$ sudo magicblueshell
Magic Blue interactive shell v0.2.2
Type "help" for a list of available commands
 help
ERROR:magicblue.magicblueshell:Unexpected error with command "": '_Helper' object has no attribute 'strip'

Ok, nevermind I had to type all commands with quotes "[COMMAND]" (i.e "help" / "set_warm_light 1.0" ect)

Thank you and sorry for the utter waste of time 😄

**Comment by Betree** [comment]
Hey jyshrpd, BluePy shoul have installed itself when running `pip install git+https://github.com/Betree/pyMagicBlue.git`. What command did you use for installing ?

Glad to see you solved everything by yourself :)

**Comment by jyshprd** [comment]
Hi Benjamin!

Thanks for taking some time to respond

I tried both :
`pip3 install git+https://github.com/Betree/pyMagicBlue.git`
`pip install git+https://github.com/Betree/pyMagicBlue.git`

Glad as well, I am off to try and figure out how Jasper and hopefully get your work running by voice command, souhaite moi bonne chance, je vais en avoir besoin aha

**Comment by Betree** [comment]
Ok good luck on your project then :)
